### ISSUE TITLE
Usage with precommit hooks

### ISSUE THREAD

**Issue by thedamon** [gagern/node-libtidy#17]
I was hoping the docs might have some more hands-on usage patterns as I have no real familiarity with the original libtidy project

I'm looking at how to get this integrated with a node script similar to how [prettier.js would work](https://github.com/prettier/prettier#pre-commit-hook) so I can have it run as a pre-commit hook through husky.

May submit a quick PR to the readme if I can figure a way to make it elegant.

**Comment by gagern** [comment]
The way I see it, this could be divided into several steps:

1. A function to load a file, prettify it then save it again unter the same or a different file name.
2. A function to take a list of files, and feed them into the above to tidy them in place.
3. A script (or pair of scripts) to do the above on the command line.
4. A `.pre-commit-hooks.yaml` as described [here](http://pre-commit.com/#new-hooks).

Each of these steps would be fairly simple, and useful on its own. Could be a single PR or multiple. In terms of API I think I'd like to use

```js
tidyFile(input, [output,] [options,] callback)
tidyFiles(files, [options,] callback)
```

These can go in `index.js`. To distinguish `output` from `options`, the former must be a native string, not an object, so that a `typeof` check can be used to distinguish them. For the scripts I'd like to see a directory called `bin` containing them.

I'd welcome one or more PRs along these lines. Thanks!

**Comment by thedamon** [comment]
That sounds like a pretty solid approach! I will look into it if time allows (time doesn't allow for much these days). 
Prettier.js is apparently in the process of adding html support so if they beat me I'll probably let 'em have it

**Comment by gagern** [comment]
Have you started any work on this yet? I *might* have some time to implement (parts of) this in the coming week, but if you are already started I'd rather give you a chance to polish it for review.

**Comment by thedamon** [comment]
Nope..! got a number of things that need getting to first ;) It'd be awesome if you had a chance

**Comment by gagern** [comment]
I think the core of what we need is done, but right now this is very brittle, because the C sources are not included, so this depends strongly on the presence of native binaries. So the next release of libtidy will probably make this usable for most people, but we need either https://github.com/pre-commit/pre-commit/pull/579 or https://github.com/pre-commit/pre-commit/pull/580 fixed before I'd call this officially supported. We also might want to add some mechanism for loading configuration data from a file inside the repository.
