### ISSUE TITLE
Release 0.3.7

### ISSUE THREAD

**Issue by jorrit** [gagern/node-libtidy#20]
I see package.json was updated to 0.3.7 but no release was pushed to npm and no tag was created in git. 
Could this be done?

**Comment by nbakken8** [comment]
I believe the optional callback in the docs will not work without this.

**Comment by gagern** [comment]
The idea is for the version number in `package.json` to get bumped straight after a binary release. This helps working on development for the next version because you can be sure that there is no outdated binary release interfering with the installation. So `package.json` not having a matching tag is working as intended. On the other hand, there have been a number of changes since the last release, so yes, perhaps I should roll a new release.

**Comment by gagern** [comment]
[Version 0.3.7](https://github.com/gagern/node-libtidy/releases/tag/v0.3.7) released. Thank you for bugging me about this, sorry it took me a while.

**Comment by jorrit** [comment]
Thanks!
