### ISSUE TITLE
npm install libtidy fails

### ISSUE THREAD

**Issue by dasmikko** [gagern/node-libtidy#5]
I'm using the latest version of Node.js and NPM

not really sure why it fails.

**Comment by balthisar** [comment]
Are you building from Tidy source? What's the description of the failure? Who's the NPM package manager? Is this better reported to them?

We have nothing officially to do with how others are packaging us, but are prepared to help if you can offer much more information.

**Comment by gagern** [comment]
Are you perhaps trying to use node-libtidy as a dependency of some other project, referencing not the latest release by version number, but actually github? In that case, you may need npm 3.7.0 to properly initialize git submodules for you. See https://github.com/npm/npm/pull/11094. This issue would manifest itself as source files not being found.

**Comment by gagern** [comment]
@balthisar: The NPM package manager would be me, and as far as I can tell, the issue was reported for my package. You just decided to watch my project, which means you'll receive notifications about all the issues reported for it. If that's not what you want, then perhaps star instead of follow would be better. Right now, this appears to be a node-specific issue, although I'll sure let you know if tidy itself is involved in some way.

**Comment by balthisar** [comment]
Oh, goodness. I feel silly.

**Comment by gagern** [comment]
Closing due to lack of response from @dasmikko. Feel free to reopen if problem persists and isn't due to uninitialized git submodules.
