### ISSUE TITLE
doc: mismatch of callback function definition. cb(err, res) vs cb(res, err)

### ISSUE THREAD

**Issue by rtack** [gagern/node-libtidy#8]
cb – callback following the callback convention, i.e. with signature function(exception, {output, errlog}).

vs 
Most asynchroneous operations in this library take a callback with the conventional node signature cb(err, res).

there might also be some confusion in the code.
cb(errlog, output); 
but then the output contains the following if there is no warning found.
e.g. console.log(output) gives the following
{ output: null,
errlog: 'No warnings or errors were found.\n\n' }

**Comment by gagern** [comment]
I get the feeling that I haven't yet understood your concerns here. I'll try to explain what I _meant_ to say, and hope you can point out where the current formulation fails to convey that meaning.

Most asynchroneous functions in the Node API take a callback as last argument, and that callback gets invoked with two arguments: an error object and the result of the operation. Usually only one of these is set, the other is `null` or undefined. Think `fs.readFile` as an example. So I'm doing the same, but for me the result in case of a successful operation is itself a combined object, containing properties like output and error log. That way I can communicate various aspects about the operation in a way that can be easily adapted by future extensions without breaking compatibility. So yes, I'm following the `cb(err, res)` scheme, but for me, `res = {output, errlog}` if it is set at all, so the signature of the callback function as a whole is indeed `function(exception, {output, errlog})`. The choice of `exception` over `err` indicates that it's only set in case of a serious error, not for every error fixed by libtidy.

The title mentions `cb(res, err)`, but I don't see that anywhere in the sources of documentation. Not sure what thats about.

That snipped `cb(errlog, output);` you quote occurs [here](https://github.com/gagern/node-libtidy/blob/f36a86f1ab6b3531727026fc920214f837e8fbd7/src/htmltidy.js#L36), in the htmltidy compatibility layer. So here I'm not following my own convention, but that of the htmltidy and htmltidy2 packages. [A few lines above](https://github.com/gagern/node-libtidy/blob/f36a86f1ab6b3531727026fc920214f837e8fbd7/src/htmltidy.js#L31) I did `output = res.output`, so while `res` is an object as you describe it, `console.log(output)` should not log an object but just the output text as a string. If you actually observed something else while using the API, please provide a bit more context.

**Comment by rtack** [comment]
> That snipped cb(errlog, output); you quote occurs here, in the htmltidy compatibility layer. So here I'm not following my own convention, but that of the htmltidy and htmltidy2 packages

I guess that's what confused me. your convention and the convention used in htmltidy are opposites. 

Add to that the fact that your callback function is "function(exception, {output, errlog})" and I was lost.
closing as I don't know how it could be made clearer without making it lengthy.
